<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

do_action( 'genesis_doctype' );
do_action( 'genesis_title' );
do_action( 'genesis_meta' ); 
?>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link href="<?php echo CHILD_URL; ?>/checkout-scripts/css/bootstrap.css" rel="stylesheet">
<link href="<?php echo CHILD_URL; ?>/checkout-scripts/css/font-awesome.min.css" rel="stylesheet" media="all">
<link href="<?php echo CHILD_URL; ?>/checkout-scripts/css/jquery.datetimepicker.css" rel="stylesheet">
<link href="<?php echo CHILD_URL; ?>/checkout-scripts/css/flat-icon/flaticon.css" rel="stylesheet">
<link href="<?php echo CHILD_URL; ?>/checkout-scripts/fancybox/jquery.fancybox.css" rel="stylesheet">
<link href="<?php echo CHILD_URL; ?>/checkout-scripts/css/style.css" rel="stylesheet">
<link href="<?php echo CHILD_URL; ?>/checkout-scripts/css/responsive.css" rel="stylesheet" media="all">
<?php
wp_head(); //* we need this for plugins
?>
</head>
<?php
genesis_markup( array(
	'html5'   => '<body %s>',
	'xhtml'   => sprintf( '<body class="%s">', implode( ' ', get_body_class() ) ),
	'context' => 'body',
) );
do_action( 'genesis_before' );

genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="wrap">',
	'context' => 'site-container',
) );

do_action( 'genesis_before_header' );
do_action( 'genesis_header' );
do_action( 'genesis_after_header' );

genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="inner">',
	'context' => 'site-inner',
) );
genesis_structural_wrap( 'site-inner' );